### ISSUE TITLE
Helm support

### ISSUE THREAD

**Issue by Lanayx** [EventStore/eventstore-docker#38]
Along with official image creation #34, it would be great to see EventStore among Helm charts there:
https://kubeapps.com/

**Comment by grigorov** [comment]
Hi all, i'm created helm chart for kubernetes. Without cluster mode, only standalone.
https://github.com/grigorov/eventstore-helm

**Comment by grigorov** [comment]
If need configure via ENV, please open issue in my repos. I will do.

**Comment by quorak** [comment]
```
apiVersion: v1
kind: Service
metadata:
  name: geteventstore
  namespace: persistance
  labels:
    db: geteventstore
spec:
  ports:
    - protocol: "TCP"
      port: 2113
      targetPort: 2113
  ports:
    - protocol: "TCP"
      port: 1113
      targetPort: 1113
  clusterIP: None
  selector:
    db: geteventstore
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geteventstore-set
  namespace: persistance
spec:
  selector:
    matchLabels:
      db: geteventstore # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: "geteventstore"
  replicas: 5
  template:
    metadata:
      labels:
        db: geteventstore # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: geteventstore
        image: eventstore/eventstore
        env: 
          - name: EVENTSTORE_INT_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: EVENTSTORE_EXT_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: EVENTSTORE_CLUSTER_DNS
            value: "geteventstore.persistance.svc.cluster.local"
          - name: EVENTSTORE_INT_TCP_PORT
            value: "1111"
          - name: EVENTSTORE_EXT_TCP_PORT
            value: "1113"
          - name: EVENTSTORE_INT_HTTP_PORT
            value: "2111"
          - name: EVENTSTORE_EXT_HTTP_PORT
            value: "2113"
          - name: EVENTSTORE_CLUSTER_SIZE
            value: "5"
          - name: EVENTSTORE_CLUSTER_GOSSIP_PORT
            value: "2111"
          - name: EVENTSTORE_GOSSIP_ALLOWED_DIFFERENCE_MS
            value: "600000"
          - name: EVENTSTORE_INT_HTTP_PREFIXES
            value: "http://*:2111/"
          - name: EVENTSTORE_EXT_HTTP_PREFIXES
            value: "http://*:2113/"
          - name: RUN_PROJECTIONS
            value: System
        ports:
          - containerPort: 2113
          - containerPort: 2111
          - containerPort: 1111
          - containerPort: 1113
        volumeMounts:
        - name: geteventstore
          mountPath: "/usr/data/eventstore"
  volumeClaimTemplates:
  - metadata:
      name: geteventstore
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
```
it is pretty much a copy from https://github.com/mastoj/eventstore-kubernetes .
This is working for me for quite a while now. But not under heavy load yet.
Will share experience.
