### ISSUE TITLE
Instructions for docker swarm mode?

### ISSUE THREAD

**Issue by drozzy** [EventStore/eventstore-docker#54]
I'm not sure, but it seems like maybe the docker swarm instructions are for the old swarm?

The use of alias is not familiar to me with the new docker swarm mode:

`docker service create --replicas 1 --name es1-node --network name=esnet,alias=escluster.net -e EVENTSTORE_CLUSTER_SIZE=3 -e EVENTSTORE_CLUSTER_DNS=escluster.net eventstore/eventstore`

Is there an example of a stack file, for docker swarm mode?

Much appreciated.

**Comment by drozzy** [comment]
In particular, I'm having trouble with making eventstore available to the internet, through the proxy ([docker-flow proxy](https://proxy.dockerflow.com/) in docker swarm).

Fyi, here is a sample stack file (docker swarm mode):

```
version: "3.6"

services:

  eventstore:
    image: eventstore/eventstore:release-4.1.1-hotfix1
    volumes:
      - /mnt/$eventstorevolumename:/var/lib/eventstore
    deploy:
      placement:
        constraints: [node.hostname == $eventstorenodename]
    environment: 
      - EVENTSTORE_RUN_PROJECTIONS=All
    networks:
      - domain
      - proxy
    labels:
      - com.df.httpsOnly=true
      - com.df.notify=true
      - com.df.servicePath=/eventstore
      - com.df.reqPathSearchReplace=/eventstore,
      - com.df.port=2113
      - comd.df.srcPort=443


networks:
  domain:
  proxy:
    external: true
```
