### ISSUE TITLE
Ho to run in-memory mode

### ISSUE THREAD

**Issue by iberodev** [EventStore/eventstore-docker#68]
With a local server I run eventstore.exe with the following arguments `--mem-db`

How to achieve this with docker?

This is my compose:
```
version: '3'
services:
    sqlserver:
        image: eventstore/eventstore
        restart: always
        ports:
            - 1113:1113
            - 2113:2113
        environment:
            - EVENTSTORE_RUN_PROJECTIONS=None
```
